/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tool_logistic_constants.h"

namespace KieShop { namespace tool {

const tool_logisticConstants g_tool_logistic_constants;

tool_logisticConstants::tool_logisticConstants() {
}

}} // namespace

