/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tool_logistic_CONSTANTS_H
#define tool_logistic_CONSTANTS_H

#include "tool_logistic_types.h"

namespace KieShop { namespace tool_logistic {

class tool_logisticConstants {
 public:
  tool_logisticConstants();

};

extern const tool_logisticConstants g_tool_logistic_constants;

}} // namespace

#endif
