/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tool_cellar_CONSTANTS_H
#define tool_cellar_CONSTANTS_H

#include "tool_cellar_types.h"

namespace KieShop { namespace tool_cellar {

class tool_cellarConstants {
 public:
  tool_cellarConstants();

};

extern const tool_cellarConstants g_tool_cellar_constants;

}} // namespace

#endif
