/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ToolCellar_H
#define ToolCellar_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "tool_cellar_types.h"

namespace KieShop { namespace tool_cellar {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ToolCellarIf {
 public:
  virtual ~ToolCellarIf() {}
  virtual void logRequest(RequestLoggingResponse& _return, const RequestLoggingRequest& req) = 0;
};

class ToolCellarIfFactory {
 public:
  typedef ToolCellarIf Handler;

  virtual ~ToolCellarIfFactory() {}

  virtual ToolCellarIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ToolCellarIf* /* handler */) = 0;
};

class ToolCellarIfSingletonFactory : virtual public ToolCellarIfFactory {
 public:
  ToolCellarIfSingletonFactory(const ::std::shared_ptr<ToolCellarIf>& iface) : iface_(iface) {}
  virtual ~ToolCellarIfSingletonFactory() {}

  virtual ToolCellarIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ToolCellarIf* /* handler */) {}

 protected:
  ::std::shared_ptr<ToolCellarIf> iface_;
};

class ToolCellarNull : virtual public ToolCellarIf {
 public:
  virtual ~ToolCellarNull() {}
  void logRequest(RequestLoggingResponse& /* _return */, const RequestLoggingRequest& /* req */) {
    return;
  }
};

typedef struct _ToolCellar_logRequest_args__isset {
  _ToolCellar_logRequest_args__isset() : req(false) {}
  bool req :1;
} _ToolCellar_logRequest_args__isset;

class ToolCellar_logRequest_args {
 public:

  ToolCellar_logRequest_args(const ToolCellar_logRequest_args&);
  ToolCellar_logRequest_args& operator=(const ToolCellar_logRequest_args&);
  ToolCellar_logRequest_args() {
  }

  virtual ~ToolCellar_logRequest_args() noexcept;
  RequestLoggingRequest req;

  _ToolCellar_logRequest_args__isset __isset;

  void __set_req(const RequestLoggingRequest& val);

  bool operator == (const ToolCellar_logRequest_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const ToolCellar_logRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ToolCellar_logRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ToolCellar_logRequest_pargs {
 public:


  virtual ~ToolCellar_logRequest_pargs() noexcept;
  const RequestLoggingRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ToolCellar_logRequest_result__isset {
  _ToolCellar_logRequest_result__isset() : success(false) {}
  bool success :1;
} _ToolCellar_logRequest_result__isset;

class ToolCellar_logRequest_result {
 public:

  ToolCellar_logRequest_result(const ToolCellar_logRequest_result&);
  ToolCellar_logRequest_result& operator=(const ToolCellar_logRequest_result&);
  ToolCellar_logRequest_result() {
  }

  virtual ~ToolCellar_logRequest_result() noexcept;
  RequestLoggingResponse success;

  _ToolCellar_logRequest_result__isset __isset;

  void __set_success(const RequestLoggingResponse& val);

  bool operator == (const ToolCellar_logRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ToolCellar_logRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ToolCellar_logRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ToolCellar_logRequest_presult__isset {
  _ToolCellar_logRequest_presult__isset() : success(false) {}
  bool success :1;
} _ToolCellar_logRequest_presult__isset;

class ToolCellar_logRequest_presult {
 public:


  virtual ~ToolCellar_logRequest_presult() noexcept;
  RequestLoggingResponse* success;

  _ToolCellar_logRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ToolCellarClient : virtual public ToolCellarIf {
 public:
  ToolCellarClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ToolCellarClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void logRequest(RequestLoggingResponse& _return, const RequestLoggingRequest& req);
  void send_logRequest(const RequestLoggingRequest& req);
  void recv_logRequest(RequestLoggingResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ToolCellarProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<ToolCellarIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ToolCellarProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_logRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ToolCellarProcessor(::std::shared_ptr<ToolCellarIf> iface) :
    iface_(iface) {
    processMap_["logRequest"] = &ToolCellarProcessor::process_logRequest;
  }

  virtual ~ToolCellarProcessor() {}
};

class ToolCellarProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ToolCellarProcessorFactory(const ::std::shared_ptr< ToolCellarIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< ToolCellarIfFactory > handlerFactory_;
};

class ToolCellarMultiface : virtual public ToolCellarIf {
 public:
  ToolCellarMultiface(std::vector<std::shared_ptr<ToolCellarIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ToolCellarMultiface() {}
 protected:
  std::vector<std::shared_ptr<ToolCellarIf> > ifaces_;
  ToolCellarMultiface() {}
  void add(::std::shared_ptr<ToolCellarIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void logRequest(RequestLoggingResponse& _return, const RequestLoggingRequest& req) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->logRequest(_return, req);
    }
    ifaces_[i]->logRequest(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ToolCellarConcurrentClient : virtual public ToolCellarIf {
 public:
  ToolCellarConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ToolCellarConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void logRequest(RequestLoggingResponse& _return, const RequestLoggingRequest& req);
  int32_t send_logRequest(const RequestLoggingRequest& req);
  void recv_logRequest(RequestLoggingResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
