/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tool_cellar_constants.h"

namespace KieShop { namespace tool_cellar {

const tool_cellarConstants g_tool_cellar_constants;

tool_cellarConstants::tool_cellarConstants() {
}

}} // namespace

