/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tool_constants.h"

namespace KieShop { namespace tool {

const toolConstants g_tool_constants;

toolConstants::toolConstants() {
}

}} // namespace

