/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tool_CONSTANTS_H
#define tool_CONSTANTS_H

#include "tool_types.h"

namespace KieShop { namespace tool {

class toolConstants {
 public:
  toolConstants();

};

extern const toolConstants g_tool_constants;

}} // namespace

#endif
