/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tool_TYPES_H
#define tool_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "base_types.h"


namespace KieShop { namespace tool {

class ShardingKeyRequest;

class ShardingKeyResponse;

typedef struct _ShardingKeyRequest__isset {
  _ShardingKeyRequest__isset() : orderId(false), isOrderId(false), isShopId(false), isUserId(false), base(false) {}
  bool orderId :1;
  bool isOrderId :1;
  bool isShopId :1;
  bool isUserId :1;
  bool base :1;
} _ShardingKeyRequest__isset;

class ShardingKeyRequest : public virtual ::apache::thrift::TBase {
 public:

  ShardingKeyRequest(const ShardingKeyRequest&);
  ShardingKeyRequest& operator=(const ShardingKeyRequest&);
  ShardingKeyRequest() : orderId(), isOrderId(0), isShopId(0), isUserId(0) {
  }

  virtual ~ShardingKeyRequest() noexcept;
  std::string orderId;
  bool isOrderId;
  bool isShopId;
  bool isUserId;
   ::base::Base base;

  _ShardingKeyRequest__isset __isset;

  void __set_orderId(const std::string& val);

  void __set_isOrderId(const bool val);

  void __set_isShopId(const bool val);

  void __set_isUserId(const bool val);

  void __set_base(const  ::base::Base& val);

  bool operator == (const ShardingKeyRequest & rhs) const
  {
    if (!(orderId == rhs.orderId))
      return false;
    if (__isset.isOrderId != rhs.__isset.isOrderId)
      return false;
    else if (__isset.isOrderId && !(isOrderId == rhs.isOrderId))
      return false;
    if (__isset.isShopId != rhs.__isset.isShopId)
      return false;
    else if (__isset.isShopId && !(isShopId == rhs.isShopId))
      return false;
    if (__isset.isUserId != rhs.__isset.isUserId)
      return false;
    else if (__isset.isUserId && !(isUserId == rhs.isUserId))
      return false;
    if (!(base == rhs.base))
      return false;
    return true;
  }
  bool operator != (const ShardingKeyRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ShardingKeyRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ShardingKeyRequest &a, ShardingKeyRequest &b);

std::ostream& operator<<(std::ostream& out, const ShardingKeyRequest& obj);

typedef struct _ShardingKeyResponse__isset {
  _ShardingKeyResponse__isset() : shardingKey(false), isNew(false), serverId(false), timestamp(false), counter(false), baseResp(false) {}
  bool shardingKey :1;
  bool isNew :1;
  bool serverId :1;
  bool timestamp :1;
  bool counter :1;
  bool baseResp :1;
} _ShardingKeyResponse__isset;

class ShardingKeyResponse : public virtual ::apache::thrift::TBase {
 public:

  ShardingKeyResponse(const ShardingKeyResponse&);
  ShardingKeyResponse& operator=(const ShardingKeyResponse&);
  ShardingKeyResponse() : shardingKey(0), isNew(0), serverId(0), timestamp(0), counter(0) {
  }

  virtual ~ShardingKeyResponse() noexcept;
  int32_t shardingKey;
  bool isNew;
  int32_t serverId;
  int32_t timestamp;
  int32_t counter;
   ::base::BaseResp baseResp;

  _ShardingKeyResponse__isset __isset;

  void __set_shardingKey(const int32_t val);

  void __set_isNew(const bool val);

  void __set_serverId(const int32_t val);

  void __set_timestamp(const int32_t val);

  void __set_counter(const int32_t val);

  void __set_baseResp(const  ::base::BaseResp& val);

  bool operator == (const ShardingKeyResponse & rhs) const
  {
    if (!(shardingKey == rhs.shardingKey))
      return false;
    if (!(isNew == rhs.isNew))
      return false;
    if (!(serverId == rhs.serverId))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(counter == rhs.counter))
      return false;
    if (!(baseResp == rhs.baseResp))
      return false;
    return true;
  }
  bool operator != (const ShardingKeyResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ShardingKeyResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ShardingKeyResponse &a, ShardingKeyResponse &b);

std::ostream& operator<<(std::ostream& out, const ShardingKeyResponse& obj);

}} // namespace

#endif
